version: "3"
services:
  infovis:
    build:
      context: https://github.com/mayerph/infovis-frontend.git
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  mariadb:
    build:
      context: https://github.com/mayerph/infovis-db.git
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: kaiserhofinfovis
